### ISSUE TITLE
PRACTICA #8 CONEXION DE BASE DE DATOS

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-m-a-r-topicos-a-p#1]
@RAEL12345 @magaly1311 @Adolfo
[PRACTICA #8.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-m-a-r-topicos-a-p/files/8672384/PRACTICA.8.pdf)
[ConexionMysql.zip](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-m-a-r-topicos-a-p/files/8672406/ConexionMysql.zip)

**Comment by SANDRAVELASCO** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
